---
settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: bluexp-relnotes
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de organización en niveles de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre la organización en niveles de BlueXP
      url: "/concept-cloud-tiering.html"
    - title: Organice en niveles los datos en las instalaciones en el cloud
      entries:
      - title: Organice en niveles Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Organice en niveles el almacenamiento de Azure Blob
        url: "/task-tiering-onprem-azure.html"
      - title: Organice en niveles Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Organice en niveles StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Organice en niveles el almacenamiento de objetos de S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Configurar la licencia
      url: "/task-licensing-cloud-tiering.html"
    - title: PREGUNTAS FRECUENTES
      url: "/faq-cloud-tiering.html"
  - title: Utiliza la organización en niveles de BlueXP
    entries:
    - title: Gestionar la organización en niveles de los datos
      url: "/task-managing-tiering.html"
    - title: Gestione el almacenamiento de objetos
      url: "/task-managing-object-storage.html"
    - title: Probar el rendimiento del cloud
      url: "/task-tiering-test.html"
    - title: Vea la información general sobre organización en niveles de todos los
        clústeres
      url: "/task-tiering-onprem-overview.html"
    - title: Supervisar el estado de las alertas de organización en niveles
      url: "/task-monitor-tiering-alerts.html"
  - title: Referencia
    entries:
    - title: Clases y regiones de almacenamiento de Amazon S3 admitidas
      url: "/reference-aws-support.html"
    - title: Niveles de acceso de Azure y regiones compatibles
      url: "/reference-azure-support.html"
    - title: Clases y regiones de almacenamiento compatibles con Google Cloud
      url: "/reference-google-support.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
