---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: La organización en niveles de BlueXP admite dos niveles de acceso y la mayoría de regiones. 
---
= Niveles de acceso de Azure Blob y regiones compatibles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La organización en niveles de BlueXP admite dos niveles de acceso y la mayoría de regiones.



== Niveles de acceso de Azure Blob compatibles

Cuando configuras la organización en niveles de los datos en Azure desde tus sistemas ONTAP on-premises, la organización en niveles de BlueXP utiliza automáticamente el nivel de acceso _Hot_ de los datos inactivos. La organización en niveles de BlueXP puede aplicar una regla de ciclo de vida en la transición de los datos del nivel de acceso _Hot_ al nivel de acceso _Cool_ tras un cierto número de días.

Si no elige el nivel de acceso _Cool_, los datos permanecerán en el nivel de acceso _Hot_ y no se aplicarán reglas.

Al configurar una regla de ciclo de vida de organización en niveles de BlueXP, no debes configurar ninguna regla de ciclo de vida al configurar el contenedor en tu cuenta de Azure.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Obtenga más información acerca de los niveles de acceso de Azure Blob"^].



== Regiones de Azure compatibles

La organización en niveles de BlueXP  admite las siguientes regiones de Azure. Las regiones de Azure China no son compatibles como destinos para la organización en niveles.



=== África

* Sudáfrica Norte




=== Asia-Pacífico

* Australia Oriental
* Australia Sureste
* Asia Oriental
* Japón este
* Japón Oeste
* Corea Central
* Corea del Sur
* Sudeste asiático




=== Europa

* Francia Central
* Alemania Oeste Central
* Alemania Norte
* Europa del Norte
* Reino Unido Sur
* Oeste del Reino Unido
* Europa Occidental




=== América del Norte

* Canada Central
* Canadá este
* Estados Unidos Central
* Este de Estados Unidos
* EE.UU. Oriental 2
* Centro Norte de Estados Unidos
* Centro Sur de EE. UU
* Oeste de EE. UU
* Oeste de EE.UU. 2
* Centro Oeste de Estados Unidos




=== Sudamérica

* Brasil Sur

