---
sidebar: sidebar 
permalink: reference-aws-support.html 
keywords: aws, amazon, s3, support, regions, storage classes 
summary: La organización en niveles de BlueXP admite varias clases de almacenamiento S3 y la mayoría de regiones. 
---
= Clases y regiones de almacenamiento S3 admitidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La organización en niveles de BlueXP admite varias clases de almacenamiento S3 y la mayoría de regiones.



== Clases de almacenamiento S3 compatibles

Cuando configuras la organización en niveles de los datos en AWS desde tus sistemas ONTAP on-premises, la organización en niveles de BlueXP utiliza automáticamente la clase de almacenamiento _Standard_ para los datos inactivos. La organización en niveles de BlueXP puede aplicar una regla de ciclo de vida en el que los datos pasan de la clase de almacenamiento _Standard_ a otra clase de almacenamiento transcurridos un cierto número de días. Puede elegir entre las siguientes clases de almacenamiento:

* Acceso estándar poco frecuente (S3 Estándar - IA)
* Una zona - Acceso poco frecuente (S3 una zona - IA)
* Organización en niveles inteligente (S3 organización en niveles inteligente)
* Recuperación instantánea de Glacier


Si no selecciona otra clase de almacenamiento, los datos permanecerán en la clase de almacenamiento _Standard_ y no se aplicarán reglas.

Al configurar una regla de ciclo de vida de organización en niveles de BlueXP, no debes configurar ninguna regla de ciclo de vida al configurar el bloque en tu cuenta de AWS.

https://aws.amazon.com/s3/storage-classes/["Obtenga información acerca de las clases de almacenamiento S3"^].



== Regiones admitidas de AWS

La organización en niveles de BlueXP admite las siguientes regiones de AWS.



=== Asia-Pacífico

* Bombay
* Seúl
* Singapur
* Sídney
* Tokio




=== Europa

* Frankfurt
* Irlanda
* Londres
* París
* Estocolmo




=== América del Norte

* Canada Central
* Este DE EE. UU. (N. Virginia)
* Este DE EE. UU. (Ohio)
* Oeste DE EE. UU. (N. California)
* Oeste DE EE. UU. (Oregón)




=== Sudamérica

* São Paulo

