---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: La organización en niveles de BlueXP admite varias clases de almacenamiento de Google Cloud y la mayoría de regiones. 
---
= Clases y regiones de almacenamiento compatibles con Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La organización en niveles de BlueXP admite varias clases de almacenamiento de Google Cloud y la mayoría de regiones.



== Clases de almacenamiento de GCP admitidas

Cuando configuras la organización en niveles de los datos en GCP desde tus sistemas ONTAP on-premises, la organización en niveles de BlueXP utiliza automáticamente la clase de almacenamiento _Standard_ para los datos inactivos. La organización en niveles de BlueXP puede aplicar una regla de ciclo de vida en el sentido de que la transición de los datos de la clase de almacenamiento _Standard_ a otras clases de almacenamiento transcurridos un cierto número de días. Puede elegir entre las siguientes clases de almacenamiento:

* Nearline
* Coldline
* Archivado


Si no selecciona otra clase de almacenamiento, los datos permanecerán en la clase de almacenamiento _Standard_ y no se aplicarán reglas.

Al configurar una regla de ciclo de vida de organización en niveles de BlueXP, no debes configurar ninguna regla de ciclo de vida al configurar el bloque en tu cuenta de Google.

https://cloud.google.com/storage/docs/storage-classes["Obtenga información sobre las clases de Google Cloud Storage"^].



== Regiones compatibles de Google Cloud

La organización en niveles de BlueXP admite las siguientes regiones.



=== América

* Iowa
* Los Ángeles
* Montreal
* N. Virginia
* Oregón
* Sao Paulo
* Carolina del Sur




=== Asia-Pacífico

* Hong Kong
* Bombay
* Osaka
* Singapur
* Sídney
* Taiwán
* Tokio




=== Europa

* Bélgica
* Finlandia
* Frankfurt
* Londres
* Países Bajos
* Zurich

