---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: Descubre las novedades en la organización en niveles de BlueXP. 
---
= Novedades de la organización en niveles de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las novedades en la organización en niveles de BlueXP.



== 4 de julio de 2023



=== Ahora puede ajustar el ancho de banda utilizado para cargar datos inactivos en el almacenamiento de objetos

Al activar la organización en niveles de BlueXP, ONTAP puede utilizar una cantidad ilimitada de ancho de banda de red para transferir los datos inactivos de los volúmenes del clúster al almacenamiento de objetos. Si observa que el tráfico por niveles afecta a las cargas de trabajo normales de usuario, puede limitar la cantidad de ancho de banda que se puede utilizar durante la transferencia. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Leer más"].



=== El evento de organización en niveles para el nivel bajo se muestra en el Centro de notificaciones

El evento de organización en niveles «Almacenar los datos adicionales del clúster <name> en el almacenamiento de objetos para aumentar la eficiencia del almacenamiento» aparece ahora como una notificación cuando un clúster está organizando en niveles menos del 20 % de sus datos inactivos, incluidos los clústeres que organizan en niveles ningún dato.

Esta notificación es una «recomendación» que pretende hacer que sus sistemas sean más eficientes y ahorrar costes de almacenamiento. Proporciona un enlace al https://bluexp.netapp.com/cloud-tiering-service-tco["Calculadora de ahorro y coste total de propiedad de la organización en niveles de BlueXP"^] para ayudarle a calcular el ahorro de costes.



== 3 de abril de 2023



=== Se ha eliminado la pestaña de licencias

La pestaña Licencias se ha eliminado de la interfaz de organización en niveles de BlueXP. Ahora, se accede a todas las licencias de suscripciones de pago por uso (PAYGO) desde la consola de organización en niveles de BlueXP en las instalaciones. También hay un enlace desde esa página a la cartera digital de BlueXP para que puedas ver y gestionar cualquier producto con tus propias licencias (BYOL) en la organización en niveles de BlueXP.



=== Se ha cambiado el nombre de las pestañas de organización en niveles y se ha actualizado el contenido

Se ha cambiado el nombre de la pestaña «Consola de clústeres» a «Clusters» y la pestaña «On-Prem Overview» se ha cambiado a «On-premises Dashboard». Estas páginas han añadido información que le ayudará a evaluar si puede optimizar el espacio de almacenamiento con una configuración adicional de organización en niveles.



== 5 de marzo de 2023



=== Ahora puede generar un informe de organización en niveles para sus volúmenes

Es posible descargar un informe en la página Tier Volumes para revisar el estado de organización en niveles de todos los volúmenes en los clústeres que se están gestionando. La organización en niveles de BlueXP genera un archivo .CSV que se puede revisar y enviar a otras personas de la empresa según sea necesario. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes["Descubra cómo descargar el informe de organización en niveles"].



== 6 de diciembre de 2022



=== Cambios de extremo de acceso saliente a Internet del conector

Debido a un cambio en la organización en niveles de BlueXP, tienes que cambiar los siguientes extremos de conector para que las operaciones de organización en niveles de BlueXP se realicen correctamente:

[cols="50,50"]
|===
| Extremo antiguo | Nuevo extremo 


| \https://cloudmanager.cloud.netapp.com | \https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
Vea la lista completa de puntos finales de la https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^], o. https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] de cloud híbrido.



== 6 de noviembre de 2022



=== Arrastra y suelta para permitir la organización en niveles de BlueXP en Azure Blob, Google Cloud Storage y StorageGRID

Si el destino de Azure Blob, Google Cloud Storage o StorageGRID Tiering existe como entorno de trabajo en el lienzo, puede arrastrar su entorno de trabajo ONTAP local al destino para iniciar el asistente de configuración de la organización en niveles.



== 19 de septiembre de 2022



=== El asistente de organización en niveles permite configurar AWS PrivateLink cuando la organización en niveles se encuentra en un almacenamiento S3

En versiones anteriores, era muy lento proporcionar esta forma segura de conectar el clúster a un bloque de S3 a través de un extremo de VPC. Ahora puede seguir los pasos de los requisitos previos a. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface["Configure el sistema para una conexión privada mediante una interfaz de extremo VPC"]Y, a continuación, puede seleccionar PrivateLink durante el asistente de configuración de capas en la página Networking.

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["Revise los requisitos y los pasos para organizar los datos inactivos en niveles en Amazon S3"].



=== Arrastre y suelte para habilitar la organización en niveles de BlueXP en Amazon S3

Si el destino de organización en niveles de Amazon S3 existe como entorno de trabajo en Canvas, puede arrastrar el entorno de trabajo de ONTAP local al destino para iniciar el asistente de configuración de organización en niveles.



=== Elija el comportamiento de organización en niveles al eliminar el almacén de objetos reflejados en una configuración de MetroCluster

Al quitar el almacén de objetos de réplica de una configuración de MetroCluster, se le preguntará si desea quitar también el almacén de objetos principal. Puede optar por mantener el almacén de objetos principal Unido al agregado o eliminarlo.



== 3 de agosto de 2022



=== Capacidad de configurar almacenes de objetos adicionales para otros agregados del clúster

La interfaz de usuario de organización en niveles en el cloud ha añadido un nuevo conjunto de páginas para la configuración del almacenamiento de objetos. Puede añadir almacenes de objetos nuevos, conectar varios almacenes de objetos a un agregado para mirroring FabricPool, cambiar los almacenes de objetos primario y de reflejo, eliminar conexiones de almacén de objetos a agregados, etc. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html["Más información acerca de la nueva funcionalidad de almacenamiento de objetos."]



=== Compatibilidad con licencias de Cloud Tiering para configuraciones de MetroCluster

Las licencias de Cloud Tiering ahora se pueden compartir con los clústeres que se encuentran en configuraciones de MetroCluster. Ya no es necesario utilizar las licencias de FabricPool obsoletas para estos casos. De este modo, es más fácil usar las licencias "flotantes" en el cloud Tiering en más clústeres. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["Consulte cómo se License y se configuran estos tipos de clústeres."]



== 3 de mayo de 2022



=== Compatibilidad con licencias de Cloud Tiering para configuraciones de clúster adicionales

Las licencias de Cloud Tiering ahora se pueden compartir con los clústeres que se encuentran en configuraciones de Tiering Mirror (no incluidas las configuraciones de MetroCluster) y con clústeres organizados en niveles en IBM Cloud Object Storage. Ya no es necesario utilizar las licencias de FabricPool obsoletas para estos casos. De este modo, es más fácil usar las licencias "flotantes" en el cloud Tiering en más clústeres. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["Consulte cómo se License y se configuran estos tipos de clústeres."]
